<a href="https://colab.research.google.com/github/Syed414/AI-Club/blob/main/my_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

importing numpy as pd


 create an array in Numpy 

In [2]:
myPythonList = [1,7,3,4]
print(myPythonList)

[1, 7, 3, 4]


 using the object np.array  using the object np.array

In [6]:
numpy_array_from_list=np.array(myPythonList)
numpy_array_from_list

array([1, 7, 3, 4])

Example

In [9]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


Adding 10 to my list.

In [11]:
a=numpy_array_from_list+10
print(a)

[11 17 13 14]


shape

In [13]:
a= np.array([1,2,3,4])
print(a.shape)
print(a.dtype)

(4,)
int64


2d array

In [14]:
c=np.array([(1,2,3,4),(5,6,7,8)])
print(c)

[[1 2 3 4]
 [5 6 7 8]]


3d- array

In [15]:
c=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


matrix with full of zeroes using np.zeroes

In [18]:
import numpy as np
x=np.zeros((2,2), dtype=np.int16)
print(x)

[[0 0]
 [0 0]]


In [19]:
import numpy as np
x=np.zeros((3,3), dtype=np.int16)
print(x)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [20]:
import numpy as np
x=np.ones((3,3), dtype=np.int16)
print(x)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Flatten Data 

In [22]:
x.flatten()


array([1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

Append data horizontally using hstack

In [26]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
print(np.hstack((f,g)))

[1 2 3 4 5 6]


Append data vertically using vstack

In [27]:
import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])
print(np.vstack((f,g)))

[[1 2 3]
 [4 5 6]]


Generate Random Numbers
syntax is numpy.random.normal(loc, scale, size)

In [28]:
normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[4.5812552  4.47824722 5.087462   4.58307126 4.79099186 4.51948131
 4.03662284 4.80873378 4.91625798 5.27566748]


In [29]:
normal_array = np.random.normal(5, 5, 10)
print(normal_array)

[10.42383397 11.22435413 -4.41482255 -7.35793964  9.08708535 -2.06051244
  2.92925971 24.6366192  -3.87335856 -1.07558383]


 numpy.arange() 
 Syntax:

numpy.arange(start, stop,step) 

In [31]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

Indexing and slicing data

In [34]:
import numpy as np
e=np.array([(1,2,3),(7,8,9)])
print(e)

[[1 2 3]
 [7 8 9]]


In [35]:
## 1st row
print(e[0])

[1 2 3]


In [36]:
## 2st row
print(e[1])

[7 8 9]


In [38]:
## 2nd col
print(e[:,1])

[2 8]


In [39]:
## 3nd col
print(e[:,2])

[3 9]


In [41]:
## 2nd row 2 values
print(e[1,:2])


[7 8]


In [43]:
##min of array
print(np.min(e))

1


In [44]:
##max of array
print(np.max(e))

9


In [45]:
##mean of array
print(np.mean(e))

5.0


In [46]:

### Median
print(np.median(e))

5.0


In [47]:
 ##Standard deviation np.std()
 print(np.std(e))

3.1091263510296048
